from enum import Enum

class Roles(str,Enum):
    University = "University"
    College = "College"
    Student = "Student"

class GenderType(str, Enum):
    male = "male"
    female = "female"
    other = "other"

class CategoryType(str, Enum):
    obc = "OBC" 
    sc = "SC"     
    st = "ST"     
    gen = "GEN"   

class StateType(str, Enum):
    andhra_pradesh = "Andhra Pradesh"
    arunachal_pradesh = "Arunachal Pradesh"
    assam = "Assam"
    bihar = "Bihar"
    chhattisgarh = "Chhattisgarh"
    goa = "Goa"
    gujarat = "Gujarat"
    haryana = "Haryana"
    himachal_pradesh = "Himachal Pradesh"
    jharkhand = "Jharkhand"
    karnataka = "Karnataka"
    kerala = "Kerala"
    madhya_pradesh = "Madhya Pradesh"
    maharashtra = "Maharashtra"
    manipur = "Manipur"
    meghalaya = "Meghalaya"
    mizoram = "Mizoram"
    nagaland = "Nagaland"
    odisha = "Odisha"
    punjab = "Punjab"
    rajasthan = "Rajasthan"
    sikkim = "Sikkim"
    tamil_nadu = "Tamil Nadu"
    telangana = "Telangana"
    tripura = "Tripura"
    uttar_pradesh = "Uttar Pradesh"
    uttarakhand = "Uttarakhand"
    west_bengal = "West Bengal"
    andaman_nicobar_islands = "Andaman and Nicobar Islands"
    chandigarh = "Chandigarh"
    dadra_nagar_haveli_daman_diu = "Dadra and Nagar Haveli and Daman and Diu"
    delhi = "Delhi"
    lakshadweep = "Lakshadweep"
    puducherry = "Puducherry"
    Jammu_and_Kashmir = "Jammu and Kashmir"
    ladakh = "Ladakh"



class UniversityType(str, Enum):
    mpuat = "Maharana Pratap University of Agriculture and Technology, Udaipur"
    rtu = "Rajasthan Technical University"
    mnit = "Malaviya National Institute of Technology"
    uiet = "University Institute of Engineering and Technology, Rajasthan"
    poornima = "Poornima University"
    nirmaan = "Nirmaan University"
    rajasthan_university = "University of Rajasthan"
    iiser = "Indian Institute of Science Education and Research, Mohali"
    bits = "Birla Institute of Technology and Science, Pilani"

class CollegeType(str, Enum):
    iit_jodhpur = "Indian Institute of Technology, Jodhpur"
    mnit = "Malaviya National Institute of Technology, Jaipur"
    rtu_kota = "Rajasthan Technical University, Kota"
    btu_bikaner = "Bikaner Technical University"
    poornima_university = "Poornima University, Jaipur"
    jnu_jaipur = "Jawaharlal Nehru University, Jaipur"
    shri_kanchipuram_college = "Shri Kanchipuram College of Engineering and Technology"
    sgsits = "S.G.S.I.T.S, Indore"
    acp = "Ajmer College of Engineering and Technology"
    aiet = "Alwar Institute of Engineering and Technology"

class DepartmentType(str, Enum):
    cse = "Computer Science and Engineering"
    ece = "Electronics and Communication Engineering"
    ee = "Electrical Engineering"
    mechanical = "Mechanical Engineering"
    civil = "Civil Engineering"
    it = "Information Technology"
    ae = "Aerospace Engineering"
    biotech = "Biotechnology"
    chemical = "Chemical Engineering"
    mining = "Mining Engineering"
    structural = "Structural Engineering"
    production = "Production Engineering"
    textile = "Textile Engineering"
    environmental = "Environmental Engineering"
    telecommunications = "Telecommunications Engineering"
    software = "Software Engineering"
    robotics = "Robotics Engineering"
    data_science = "Data Science and Engineering"
    ai = "Artificial Intelligence"

class CourseType(str, Enum):
    Btech = "Btech"
    Mtech = "Mtech"
    Phd = "Phd"

class BranchType(str, Enum):
    cse = "Computer Science and Engineering"
    ece = "Electronics and Communication Engineering"
    ee = "Electrical Engineering"
    mechanical = "Mechanical Engineering"
    civil = "Civil Engineering"
    it = "Information Technology"
    ae = "Aerospace Engineering"
    biotech = "Biotechnology"
    chemical = "Chemical Engineering"
    mining = "Mining Engineering"
    structural = "Structural Engineering"
    production = "Production Engineering"
    textile = "Textile Engineering"
    environmental = "Environmental Engineering"
    telecommunications = "Telecommunications Engineering"
    software = "Software Engineering"
    robotics = "Robotics Engineering"
    data_science = "Data Science and Engineering"
    ai = "Artificial Intelligence"

class JobModeType(str, Enum):
    remote = "Remote"
    onsite = "Onsite"
    hybrid = "Hybrid"
    offline = "Offline"
    freelance = "Freelance"
    contract = "Contract"